Completed Bubble_Sort Project
angelacuahutle/Ruby_bubble_sort pull request #1
Opened 2021-01-23 02:30 UTC by angelacuahutle

In this project, We implemented the bubble sort algorithm using Ruby. We understood each part of this method.

2021-01-23 03:09 UTC, BrianSammit requested changes
REQUIRED CHANGES :recycle: 
------------
Hello team :wave:  Excellent job you did so far :muscle: 
However, there are somethings that you forget to do. :thinking: 
------------

- [x] You forgot to do the #bubble_sort_by method. you can find the specifications [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/).

![Screenshot from 2021-01-22 22-03-27](https://user-images.githubusercontent.com/64173189/105567066-acc4ec00-5cfd-11eb-8718-609dc4ea0923.png)

--------------------------
Make these changes and request for another review. :smile: 
HAPPY CODING!! 

![200 (1)](https://user-images.githubusercontent.com/64173189/105567143-3bd20400-5cfe-11eb-99df-5c2dabe81371.gif)

2021-01-23 03:09 UTC, BrianSammit commented on README.md
> +Run the command $ ruby bubble_sort.rb
You can improve this using bullet points.
Example:
- Open terminal 
- $ git clone where you want the project.
- ...

2021-01-23 03:09 UTC, BrianSammit commented on README.md
> +### Install
You are not using this, please delete it or use it to improve your Readme.

2021-01-27 20:42 UTC, angelacuahutle commented
Made changes as suggested:

- We build the #bubble_sort_by method.
- Fixed Readme file. 
- Setup and installed linters

2021-01-27 21:13 UTC, GzimAsani approved these changes
# Approved ✅

## You have done a great  job making this and improving the code based on the previous review 👏🧨💪!

### You have met all the requirements of the project. Go ahead and merge it! 🚀 !

_Please check the optional changes for the README file which suggestions will make it look more professional!_
<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:
Happy coding 👨‍💻

2021-01-27 21:13 UTC, GzimAsani commented on README.md
> +
[Optional] - There is no live demo for this project so kindly remove this

2021-01-27 21:13 UTC, GzimAsani commented on README.md
> +### Install
Also remove these since you are not using them

2021-01-27 23:29 UTC, angelacuahutle commented
Project approved

2021-01-27 23:29 UTC, merged